[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "16.20.0"
  NPM_FLAGS = "--legacy-peer-deps"

[[edge_functions]]
  function = "tldr-redirect"
  path = "/*"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200