// Email send
export const EMAIL_LOADING = 'EMAIL_LOADING'
export const EMAIL_LOADING_COMPLETE = 'EMAIL_LOADING_COMPLETE'
export const EMAIL_RESET = 'EMAIL_RESET'
export const EMAIL_ERROR = 'EMAIL_ERROR'
export const EMAIL_ERROR_RESET = 'EMAIL_ERROR_RESET'